import './globals.css'
import { Poppins } from 'next/font/google'
import Header from './components/Header'

const poppins = Poppins({
  weight: ['400', '700'], 
  subsets: ['latin']
}) 

export const metadata = {
  title: 'Gachiri Mwangi',
  description: 'Generated by create next app',
  keywords: 'HTML, CSS, JAVASCRIPT, REACT, NEXTJS'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <main className='container'>          
 {children}
        </main>
       
        </body>
    </html>
  )
}
